#ifndef __DEFINITION_H__
#define __DEFINITION_H__

#define REGION_WIDTH 16
#define REGION_HEIGHT 128
#define GEOM_SIZE REGION_WIDTH
#define GEOM_COUNT REGION_HEIGHT / GEOM_SIZE
#define NUM_OCTAVES 1
#define PERSON_HEIGHT 1.8
#define CUBS_IN_GEOM REGION_WIDTH * REGION_WIDTH * REGION_WIDTH

#endif
